[package]
name = "hermit_bench"
version = "0.1.0"
edition = "2024"


[dependencies]
hermit = { path = "../new/hermit-rs/hermit" }
[target.'cfg(target_os = "hermit")'.dependencies]
rand = { version = "0.8", features = ["std_rng"] } 
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

